const decoder = new TextDecoder();
const encoder = new TextEncoder();
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
export class AdvancedStudio{
  constructor(root,api){this.root=root;this.api=api;this.build();}
  build(){this.root.innerHTML=`<section class="advanced"><div class="advanced-tabs"><button data-tab="problems" class="active">Problems</button><button data-tab="raw">Raw files</button><button data-tab="ctm">CTM Builder</button><button data-tab="cit">CIT Builder</button></div><div id="advancedBody" class="advanced-body"></div></section>`;this.root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));this.show(b.dataset.tab);});this.show('problems');}
  show(tab){if(tab==='problems')this.problems();else if(tab==='raw')this.raw();else if(tab==='ctm')this.ctm();else this.cit();}
  problems(){const ps=this.api.problems();const b=this.root.querySelector('#advancedBody');b.innerHTML=`<div class="panel-head"><div><span class="eyebrow">LIVE VALIDATION</span><h2>${ps.length} problem${ps.length===1?'':'s'}</h2></div><button id="rerunValidation" class="secondary">Re-run</button></div><div class="problem-list">${ps.length?ps.map(p=>`<div class="problem ${p.severity}"><span class="severity">${p.severity.toUpperCase()}</span><div><strong>${esc(p.path)}</strong><p>${esc(p.message)}</p></div></div>`).join(''):'<div class="empty-card">No structural problems detected.</div>'}</div>`;b.querySelector('#rerunValidation').onclick=()=>{this.api.revalidate();this.problems();};}
  raw(){const entries=this.api.entries().filter(e=>/\.(json|mcmeta|properties|txt)$/i.test(e.path));const b=this.root.querySelector('#advancedBody');b.innerHTML=`<div class="raw-layout"><div class="raw-list"><input id="rawSearch" placeholder="Filter text files…">${entries.map(e=>`<button data-path="${e.path.replace(/"/g,'&quot;')}">${esc(e.path)}</button>`).join('')}</div><div class="raw-editor"><div class="raw-toolbar"><code id="rawPath">Select a file</code><button id="rawSave" class="primary">Save</button></div><textarea id="rawText" spellcheck="false"></textarea></div></div>`;let selected='';const ta=b.querySelector('#rawText');b.querySelectorAll('[data-path]').forEach(btn=>btn.onclick=()=>{selected=btn.dataset.path;b.querySelector('#rawPath').textContent=selected;ta.value=decoder.decode(this.api.getFile(selected).data);});b.querySelector('#rawSave').onclick=async()=>{if(!selected)return;await this.api.updateFile(selected,encoder.encode(ta.value));this.api.toast('Raw file saved.','success');};b.querySelector('#rawSearch').oninput=e=>{const q=e.target.value.toLowerCase();b.querySelectorAll('[data-path]').forEach(x=>x.hidden=!x.dataset.path.toLowerCase().includes(q));};}
  ctm(){const b=this.root.querySelector('#advancedBody');b.innerHTML=`<div class="builder"><span class="eyebrow">OPTIFINE 1.8.9</span><h2>Connected Textures builder</h2><div class="builder-grid"><label>Properties path<input id="ctmPath" value="assets/minecraft/mcpatcher/ctm/custom/block.properties"></label><label>Method<select id="ctmMethod"><option>ctm</option><option>horizontal</option><option>vertical</option><option>random</option><option>repeat</option><option>fixed</option></select></label><label>Match blocks<input id="ctmMatch" placeholder="20 20:1"></label><label>Tiles<input id="ctmTiles" value="0-46"></label></div><div class="ctm-preview" id="ctmPreview">47-tile CTM preset</div><button id="ctmSave" class="primary">Create / update CTM properties</button></div>`;b.querySelector('#ctmMethod').onchange=e=>b.querySelector('#ctmPreview').textContent=e.target.value==='ctm'?'47-tile CTM preset':`${e.target.value} method`;b.querySelector('#ctmSave').onclick=async()=>{const lines=[`method=${b.querySelector('#ctmMethod').value}`,b.querySelector('#ctmMatch').value.trim()&&`matchBlocks=${b.querySelector('#ctmMatch').value.trim()}`,`tiles=${b.querySelector('#ctmTiles').value.trim()}`].filter(Boolean).join('\n')+'\n';await this.api.updateFile(b.querySelector('#ctmPath').value.trim(),encoder.encode(lines));this.api.toast('CTM properties saved.','success');};}
  cit(){const b=this.root.querySelector('#advancedBody');b.innerHTML=`<div class="builder"><span class="eyebrow">OPTIFINE 1.8.9 · MCPATCHER/CIT</span><h2>Custom Item Texture rule</h2><div class="builder-grid"><label>Properties path<input id="citPath" value="assets/minecraft/mcpatcher/cit/custom_item.properties"></label><label>Items<input id="citItems" placeholder="276 267"></label><label>Texture<input id="citTexture" placeholder="custom_item"></label><label>Damage<input id="citDamage" placeholder="0-50%"></label><label>Enchantments<input id="citEnchant" placeholder="sharpness"></label><label>Name/NBT rule<input id="citNbt" placeholder="nbt.display.Name=ipattern:*Blue*"></label></div><button id="citSave" class="primary">Create CIT rule</button></div>`;b.querySelector('#citSave').onclick=async()=>{const pairs=[['type','item'],['items',b.querySelector('#citItems').value],['texture',b.querySelector('#citTexture').value],['damage',b.querySelector('#citDamage').value],['enchantmentIDs',b.querySelector('#citEnchant').value]];let s=pairs.filter(([,v])=>v.trim()).map(([k,v])=>`${k}=${v.trim()}`).join('\n');const nbt=b.querySelector('#citNbt').value.trim();if(nbt)s+='\n'+nbt;s+='\n';await this.api.updateFile(b.querySelector('#citPath').value.trim(),encoder.encode(s));this.api.toast('CIT rule saved.','success');};}
}
