const decoder = new TextDecoder();
const encoder = new TextEncoder();

function parseProps(s) { const out={}; for(const line of s.split(/\r?\n/)){const t=line.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i>0)out[t.slice(0,i).trim()]=t.slice(i+1).trim();} return out; }
function emitProps(obj) { return Object.entries(obj).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>`${k}=${v}`).join('\n')+'\n'; }

export class SkyStudio {
  constructor(root, api){this.root=root;this.api=api;this.path='';this.props={};this.objectUrl='';this.build();}
  build(){
    this.root.innerHTML=`<section class="studio-layout sky-layout"><div class="studio-main"><div class="studio-title"><div><span class="eyebrow">OPTIFINE 1.8.9 · MCPATCHER</span><h2>Sky Studio</h2></div><button id="saveSky" class="primary">Save sky layer</button></div><div class="sky-preview" id="skyPreview"><div class="sun"></div><div class="sky-grid"></div><div class="time-label" id="timeLabel">12:00</div></div><input id="timeRange" class="time-range" type="range" min="0" max="24000" value="6000"><div class="sky-timeline"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div></div><aside class="inspector"><div class="inspector-head"><span>Sky layer</span><span class="badge">world0</span></div><label>Existing layer<select id="skyFile"></select></label><label>Save path<input id="skyPath" value="assets/minecraft/mcpatcher/sky/world0/sky1.properties"></label><label>Source<input id="skySource" value="./sky1.png"></label><div class="two-col"><label>Fade in start<input id="startFadeIn" value="18:00"></label><label>Fade in end<input id="endFadeIn" value="19:30"></label></div><div class="two-col"><label>Fade out end<input id="endFadeOut" value="05:30"></label><label>Blend<select id="blend"><option>add</option><option>alpha</option><option>replace</option><option>multiply</option><option>screen</option><option>overlay</option></select></label></div><label class="check"><input id="rotate" type="checkbox"> Rotate layer</label><div class="two-col"><label>Speed<input id="speed" type="number" step="0.05" value="1"></label><label>Axis<input id="axis" value="0.0 0.0 1.0"></label></div><div class="hint">Sky files are generated under <code>assets/minecraft/mcpatcher/sky/</code>, matching the 1.8.9-era OptiFine layout.</div></aside></section>`;
    this.root.querySelector('#skyFile').onchange=e=>this.load(e.target.value); this.root.querySelector('#saveSky').onclick=()=>this.save(); this.root.querySelector('#timeRange').oninput=e=>this.preview(Number(e.target.value)); ['skySource','blend','rotate','speed','axis'].forEach(id=>this.root.querySelector('#'+id).addEventListener('input',()=>this.preview(Number(this.root.querySelector('#timeRange').value))));
  }
  refreshList(){const arr=this.api.entries().filter(e=>/mcpatcher\/sky\/.*\.properties$/i.test(e.path));this.root.querySelector('#skyFile').innerHTML='<option value="">New layer…</option>'+arr.map(e=>`<option value="${e.path}">${e.path}</option>`).join('');}
  async load(path){if(!path)return;const e=this.api.getFile(path);if(!e)return;this.path=path;this.props=parseProps(decoder.decode(e.data));this.root.querySelector('#skyPath').value=path;for(const id of ['source','startFadeIn','endFadeIn','endFadeOut','blend','speed','axis']){const el=this.root.querySelector('#'+(id==='source'?'skySource':id));if(el&&this.props[id]!=null)el.value=this.props[id];}this.root.querySelector('#rotate').checked=this.props.rotate==='true';await this.preview(Number(this.root.querySelector('#timeRange').value));}
  resolveSource(){const path=this.root.querySelector('#skyPath').value.trim();const source=this.root.querySelector('#skySource').value.trim();if(!source)return'';if(!source.startsWith('./'))return source.replace(/^\/+/, '');return path.slice(0,path.lastIndexOf('/')+1)+source.slice(2);}
  async preview(t){const h=((t/1000+6)%24+24)%24;this.root.querySelector('#timeLabel').textContent=`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.floor((h%1)*60)).padStart(2,'0')}`;const p=this.root.querySelector('#skyPreview');const light=Math.max(0.05,Math.sin((h-6)/24*Math.PI*2)*0.5+0.5);p.style.setProperty('--daylight',light.toFixed(2));const src=this.resolveSource();const e=this.api.getFile(src);if(e){URL.revokeObjectURL(this.objectUrl);this.objectUrl=URL.createObjectURL(new Blob([e.data],{type:'image/png'}));p.style.backgroundImage=`linear-gradient(rgba(5,9,20,${1-light}),rgba(5,9,20,${1-light})),url("${this.objectUrl}")`;}else p.style.backgroundImage='linear-gradient(180deg,#174b78,#829ac0 55%,#e8b37b)';}
  async save(){const path=this.root.querySelector('#skyPath').value.trim();if(!path)return;const props={source:this.root.querySelector('#skySource').value.trim(),startFadeIn:this.root.querySelector('#startFadeIn').value.trim(),endFadeIn:this.root.querySelector('#endFadeIn').value.trim(),endFadeOut:this.root.querySelector('#endFadeOut').value.trim(),blend:this.root.querySelector('#blend').value,rotate:String(this.root.querySelector('#rotate').checked),speed:this.root.querySelector('#speed').value,axis:this.root.querySelector('#axis').value.trim()};await this.api.updateFile(path,encoder.encode(emitProps(props)));this.api.toast('Sky layer saved.','success');this.refreshList();}
}
