import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const assert=(c,m)=>{if(!c)throw new Error(m)};
const html=read('index.html'),css=read('styles.css'),app=read('src/app.js'),manifest=JSON.parse(read('manifest.webmanifest')),sw=read('sw.js');
assert(html.includes('id="editor-main"'),'main landmark missing');
assert((html.match(/role="tab"/g)||[]).length===5,'expected five workspace tabs');
for(const id of ['tab-texture','tab-animation','tab-model','tab-sky','tab-advanced'])assert(html.includes(`id="${id}"`),`missing ${id}`);
assert(html.includes('id="pack-file-input"')&&html.includes('type="file"'),'native ZIP input missing');
assert(html.includes('id="toast-region"')&&html.includes('aria-live="polite"'),'live region missing');
assert(html.includes('ZIP resource packs only')&&html.includes('id="drop-overlay"'),'ZIP constraints/drop overlay missing');
assert(css.includes('--bg: #f6f7f9')&&css.includes('--surface: #ffffff')&&css.includes('--accent: #f6b80a'),'bright tokens missing');
assert(css.includes('@media (pointer: coarse)')&&css.includes('min-height: 44px'),'coarse targets missing');
assert(css.includes('@media (prefers-reduced-motion: reduce)'),'reduced motion missing');
assert(app.includes('showModalWithFocusRestore'),'focus restore helper missing');
assert(app.includes("setAttribute('aria-selected'"),'tab selected state missing');
assert(app.includes("panel.setAttribute('role','dialog')")&&app.includes("panel.setAttribute('aria-modal','true')"),'drawer modal semantics missing');
assert(app.includes('logicalGrid()')&&app.includes('availableGrids'),'resolution grid missing');
assert(app.includes("document.addEventListener('dragenter'")&&app.includes('handleDroppedFiles'),'drag/drop ZIP path missing');
for(const icon of ['./icons/icon-192.png','./icons/icon-512.png','./icons/icon.svg'])assert(manifest.icons.some(i=>i.src===icon),`manifest missing ${icon}`);
for(const file of ['icons/icon-192.png','icons/icon-512.png','icons/icon.svg'])assert(fs.existsSync(file),`missing ${file}`);
for(const file of ['./index.html','./styles.css','./manifest.webmanifest','./icons/icon.svg','./icons/icon-192.png','./icons/icon-512.png','./src/app.js','./src/zip.js','./src/storage.js','./src/validators.js'])assert(sw.includes(`'${file}'`),`service worker missing ${file}`);
console.log('UI static checks PASS');
